version: '3.7'

services:
  estoque_api:
    container_name: estoque_api
    build: 
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    env_file:
      - ./.env
    depends_on:
      - database_estoque_api
  database_estoque_api:
    container_name: database_estoque_api
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - /var/cache/postgres_data:/var/lib/postgresql/data
  database_estoque_api_test:
    container_name: database_estoque_api_test
    image: postgres
    ports:
      - 5433:5432
    env_file:
      - ./.env
    volumes:
      - /var/cache/postgres_data_test:/var/lib/postgresql/data
  